### ISSUE TITLE
Make `_AsyncStream` and friends in stub files public

### ISSUE THREAD

**Issue by james-smith-za** [ska-sa/spead2#147]
The documentation shows an `AbstractStream` class which isn't reflected in any of the actual stub files:
https://spead2.readthedocs.io/en/latest/py-send.html#spead2.send.asyncio.AbstractStream

This was making mypy complain in katgpucbf. The current workaround is to use the _AsyncStream class, but this is "private", so it shouldn't really be relied upon.

I haven't checked, but there may well be other such "private" classes in the stub files which may be more useful as public ones.

**Comment by bmerry** [comment]
The documentation does say "They implement the following abstract interface (the class does not actually exist):", but it is useful to have base types that can be used for type annotations.

**Comment by bmerry** [comment]
After some thought, I think for now let's just rename `_SyncStream` and `_AsyncStream` both to `AbstractStream` (they're in different modules so they won't collide), and update the docs to say that while AbstactStream doesn't exist at runtime it can be used for type annotations. The other private classes in the .pyi files are to capture the functionality that is shared between sync and async streams, but I'm expecting that any user code will use one or the other, and if one really wants to accept both then `Union` will suffice.
