### ISSUE TITLE
Provide integration with asyncio in Python 3

### ISSUE THREAD

**Issue by bmerry** [ska-sa/spead2#18]
One can currently integrate with trollius and trollius has some degree of integration with asyncio, but it would be nice to provide a direct asyncio integration as well, so that users do not need to install trollius.

**Comment by juandesant** [comment]
Agreed; [`trollius` is now officially deprecated][1], and `asyncio` is standard since Python 3.4

[1]: http://trollius.readthedocs.io/deprecated.html#deprecated "Trollius is deprecated"

**Comment by bmerry** [comment]
Implemented in 1.5.0 (although not yet well documented).

**Comment by rtobar** [comment]
Hi Bruce,

Somehow related to this, the asyncio-related python modules are present in the source distributions of `spead2` but actually not in the git repository itself. Is there a reason for this, or is it simply an oversight? I compiled `spead2` from the repository today and was surprised to find these modules missing. Getting them from a PyPI source distribution and putting them in the correct place did the trick.

Thanks for your comments,
Rodrigo

**Comment by bmerry** [comment]
They're not checked in because they're generated - running ./bootstrap.sh should generate them.

**Comment by bmerry** [comment]
Looks like I forgot to close this issue when it was implemented - closing it now.

**Comment by rtobar** [comment]
Thanks for the swift response! I imagined there had to be a reason for this, but failed to find the source of the files.
