### ISSUE TITLE
Multi-packet heap with stop control will lose the data in that heap

### ISSUE THREAD

**Issue by bmerry** [ska-sa/spead2#29]
Currently, as soon as a packet with a stop control flag is seen, everything gets shut down. However, nothing in the protocol prevents the stop heap from having lots of data spread over multiple heaps (even though this is not how it is typically used for KAT). In such cases, we could wait until the heap is complete before shutting everything down.

This might be WONTFIXed, because making that change increases the risk that other packets in that heap could get lost, leading to a deadlock where the consumer never gets to see the stop packet because it is in a partial heap. A possible workaround is to add a timeout to ensure that everything gets shut down within a short interval of seeing a stop packet.

It is probably best if stop packets contain nothing but the stop control, however.

**Comment by sratcliffe** [comment]
Fully in agreement with the final statement that stop packets are exclusively for control and content is discarded.

Stop is something that really must work as reliably as possible.

**Comment by bmerry** [comment]
Yeah, this is starting to make we come around to your view that a heap with a stop flag shouldn't even show up through the iterator: since a stop heap with data doesn't work in all cases, it should rather not work at all.
