### ISSUE TITLE
MAP_ANONYMOUS not defined on Mac OS

### ISSUE THREAD

**Issue by fdulwich** [ska-sa/spead2#49]
Compilation fails on Mac OS 10.10 because MAP_ANONYMOUS is not defined:

src/common_memory_allocator.cpp:71:29: error: use of undeclared identifier 'MAP_ANONYMOUS'
        int use_flags = flags | MAP_ANONYMOUS | MAP_PRIVATE

Changing it to MAP_ANON appears to fix it.

Best wishes, Fred

**Comment by bmerry** [comment]
Thanks for the report. I've pushed a change to master that should fix it - if it doesn't, let me know.

**Comment by fdulwich** [comment]
Confirming that master now compiles successfully here - thank you!
