### ISSUE TITLE
Test suite hangs

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/spead2#62]
When running the test suite I experience a hang.

cmd: `$ python2.7 -m nose -vvv`
https://gist.github.com/gijzelaerr/86f69508823a26bde5b97c98c07c1ab4

**Comment by bmerry** [comment]
It Works For Me (tm). What I've seen cause inconsistent behaviour across systems in the past is whether "localhost" resolves to an IPv4 or an IPv6 address (or both), which can cause the expected traffic to get lost. Maybe check if there are instances of localhost still in the test case and change it to either 127.0.0.1 or ::1 depending on whether it is an IPv4 or IPv6 test (tests are IPv4 unless otherwise noted).

**Comment by gijzelaerr** [comment]
localhost config looks fine to me (ubuntu 18.04, by te way).
```$  host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1
```

**Comment by gijzelaerr** [comment]
replacing localhost with IP addresses doesn't solve the issue.

BTW, i'm making a KERN package for spead2, i'll just disable the test suite for now. Uploading to KERN-4 and KERN-dev as we speak.

**Comment by bmerry** [comment]
I wonder if it's doing some sort of round-robin and giving the sender IPv4 and the receiver IPv6 or vice versa.

Packaging sounds great. Some things to be aware of though:
- configure checks for CPU support for MOVNTDQ (an SSE2 instruction). That's fine for amd64 (where SSE2 is always available), but if you're making i386 packages and care about really old hardware, you might need to do something about it (configure takes --without-movntdq to disable detection, but there's currently no way to pass that through setup.py).
- There are several features that get enabled if the relevant libraries are found at build time. It would be nice to build-depends on libpcap, librdmacm and libibverbs (and depend on the runtime libraries too).

**Comment by gijzelaerr** [comment]
1> we only make amd64 packages. 

2> all done! https://github.com/kernsuite-debian/spead2/blob/master/debian/control#L27

**Comment by bmerry** [comment]
Did you ever figure this out Gijs? If it's still happening with 1.10.0, maybe see if you can provide a Docker container which reproduces the problem?

**Comment by gijzelaerr** [comment]
i've disabled the test suite so i don't know, and it hasn't a high priority enough issue for me to look into this until now.

**Comment by bmerry** [comment]
I'm going to close because I can't reproduce it. @gijzelaerr, if you find time to investigate it you can re-open.
