### ISSUE TITLE
pybind11 not found while compiling 1.9.2

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/spead2#63]
```
pybind11 not found. Either download a release from https://pypi.python.org/pypi/spead2 or run git submodule update --init --recursive if not using a release.
```
but i have `pybind11-dev  2.0.1-4   ` installed

**Comment by bmerry** [comment]
spead2 uses a vendored pybind11, which is a git submodule if you're pulling from github. Do you have a (non-empty) 3rdparty/pybind11 directory?

**Comment by gijzelaerr** [comment]
I automatically download the release tarball from github, and this doesn't seem to contain that folder.

**Comment by bmerry** [comment]
Did you download the one named "Source code"? That one is generated by Github and isn't a proper release. Use https://github.com/ska-sa/spead2/releases/download/v1.9.2/spead2-1.9.2.tar.gz

**Comment by gijzelaerr** [comment]
that solves the problem, thanks.
