### ISSUE TITLE
Missing header installs spead2/common_ibv_loader.h

### ISSUE THREAD

**Issue by ewanbarr** [ska-sa/spead2#72]
Looks like there is a missing header install in the spead2 build:

`/usr/local/include/spead2/common_ibv.h:28:38: fatal error: spead2/common_ibv_loader.h: No such file or directory`

This file is needed for applications that are built against spead2.

**Comment by bmerry** [comment]
If you're building from Git (rather than downloading a release tarball) then you'll need to run `./bootstrap.sh` to generate that file.

**Comment by ewanbarr** [comment]
The `./bootstrap` call is not the issue. This is correctly generating the file. It is the `make install` call that is subsequently not putting this file into the target install directory.

**Comment by bmerry** [comment]
Ah, I understand now. I'll get it fixed (just as soon as I remind myself how to beat automake into doing it).

**Comment by bmerry** [comment]
@ewanbarr: version 1.13.1 should fix this.
