### ISSUE TITLE
Compilation fails with MLNX_OFED 5.0

### ISSUE THREAD

**Issue by bmerry** [ska-sa/spead2#90]
This is reported by @ajameson:
```
libspead2.a(common_ibv.o): In function spead2::ibv_mr_t::ibv_mr_t(spead2::ibv_pd_t const&, void*, unsigned long, int)': common_ibv.cpp:(.text+0x828): undefined reference to ibv_reg_mr'
```
The problem is that RDMA-Core now defines `ibv_reg_mr` as a [macro](https://github.com/linux-rdma/rdma-core/blob/7af01c79e00555207dee6132d72e7bfc1bb5485e/libibverbs/verbs.h#L2426), which prevents the loader from functioning correctly.

**Comment by ajameson** [comment]
Thanks @bmerry, to be clear, this macro definition is not an issue in OFED 4.7-3.2.9.0, but is introduced in 5.0-2.1.8.0.
